---
title: "test objectives"
output: html_document
date: '2022-03-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
librarian::shelf(prioritizr)

# load data
data(sim_pu_raster, sim_features, sim_phylogeny)

# create base problem
p <- problem(sim_pu_raster, sim_features) %>%
     add_relative_targets(0.1) %>%
     add_binary_decisions() %>%
     add_default_solver(verbose = FALSE)

 # create problem with added minimum set objective
p1 <- p %>% add_min_set_objective()

# create problem with added maximum coverage objective
# note that this objective does not use targets
p2 <- p %>% add_max_cover_objective(500)

# create problem with added maximum feature representation objective
p3 <- p %>% add_max_features_objective(1900)

# create problem with added minimum shortfall objective
p4 <- p %>% add_min_shortfall_objective(1900)

# create problem with added minimum largest shortfall objective
p5 <- p %>% add_min_largest_shortfall_objective(1900)

# create problem with added maximum phylogenetic diversity objective
p6 <- p %>% add_max_phylo_div_objective(1900, sim_phylogeny)

# create problem with added maximum phylogenetic diversity objective
p7 <- p %>% add_max_phylo_end_objective(1900, sim_phylogeny)

# create problem with added maximum utility objective
# note that this objective does not use targets
p8 <- p %>% add_max_utility_objective(1900)

# \dontrun{
# solve problems
s <- stack(solve(p1), solve(p2), solve(p3), solve(p4), solve(p5), solve(p6),
           solve(p7), solve(p8))

# plot solutions
plot(s, axes = FALSE, box = FALSE,
     main = c("min set", "max coverage", "max features",
              "min shortfall", "min largest shortfall",
              "max phylogenetic diversity",
              "max phylogenetic endemism", "max utility"))

# }

```

