---
title: "data_prep"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get HexIDs for High Seas

- [bbnj::p_abnj](https://benioffoceaninitiative.github.io/bbnj/reference/p_abnj.html)
- https://github.com/crazycapivara/h3-r/blob/master/inst/examples/nc-polyfill.R

- [h3:polyfill](https://crazycapivara.github.io/h3-r/reference/polyfill.html)\
  Get all hexagons with centers contained in a given polygon\
  `hex_ids <- polyfill(bbnj::p_abnj)`
  
- [h3::h3_set_to_multi_polygon](https://crazycapivara.github.io/h3-r/reference/h3_set_to_multi_polygon.html)\
  Create a (multi) polygon describing the outline(s) of a set of hexagons
  `hex_sf <- h3::h3_set_to_multi_polygon(hex_ids)`
  analyze existing raster layers with these to populate planning units and features for prioritizr

```{r}
# install.packages("crazycapivara/h3-r")
librarian::shelf(
  BenioffOceanInitiative/bbnj,
  crazycapivara/h3)

bbnj::p_abnj
```

