---
title: "Solutions 4 - rescale"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: hide
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

Cumulative sum plots of layers for determining target per layer and allowing weights to have differential impact on scenario solution.

## Get planning units as hexagons

```{r pu}
# remotes::install_github("BenioffOceanInitiative/bbnj")
# devtools::install_local("../bbnj")
librarian::shelf(
  BenioffOceanInitiative/bbnj, dplyr, DT,
  exactextractr, fs, ggplot2, glue, h3, here, mapview, 
  prioritizr,
  purrr, raster, readr, rlang, scales, sf, stringr, 
  tibble,  tidyr, units)
source(here("libs/plots.R"))
select <- dplyr::select
mapviewOptions(fgb = FALSE)
mapviewOptions(
  vector.palette = mapviewPalette("mapviewSpectralColors"))
# devtools::load_all(here("~/Github/bbest/prioritizr"))
# devtools::install_local(here("~/Github/bbest/prioritizr"))

#install.packages("/Library/gurobi951/macos_universal2/R/gurobi_9.5-1_R_4.1.1.tgz")
# copied into /Library/Frameworks/R.framework/Versions/4.2/Resources/library/gurobi

hex_res <- 4 # 2
hex_geo <- glue("data/abnj_hex_res{hex_res}.geojson")
pu_rds  <- glue("data/abnj_hex_res{hex_res}_area.rds")
if (!file.exists(pu_rds)){
  
  pu <- read_sf(hex_geo)
  
  # calculate area
  pu <- pu %>%
    # st_make_valid() %>%      # dateline issues
    filter(st_is_valid(.)) %>% # 8 hexagons dropped 
    mutate(
      area_km2 = st_area(geometry) %>% 
        set_units(km^2) %>% 
        drop_units(),
      area_pct = area_km2 / sum(area_km2))
  # sum(pu$area_pct) # check adds to 12

  saveRDS(pu, file = pu_rds)
} else {
  pu <- readRDS(pu_rds)
  # paste(names(pu), collapse = ", ")
  # hexid, on_dtln, lon, lat, FID, geometry, area_km2, area_pct
}

# mapview(pu, zcol="area_pct")
# plot(pu)
```

## Get layers

```{r lyrs7}
lyrs7_grd <- here("data/lyrs7_mol.grd")

if (!file.exists(lyrs7_grd)){
  tifs1 <- list.files(here("../bbnj-scripts/map_layers"), "tif$", full.names = T)
  tifs2 <- list.files(here("../bbnj-scripts/presentation_maps"), "tif$", full.names = T)[-1] # drop redundant bio_vgpm.tif
  lyrs <- stack(c(tifs1, tifs2))
  sort(names(lyrs))
  
  s_nspp <- subset(lyrs, sort(names(lyrs))[26:48])
  r_nspp <- calc(s_nspp, sum, na.rm = T)
  
  s_mounts <- subset(lyrs, sort(names(lyrs))[49:51])
  r_mounts <- calc(s_mounts, sum, na.rm = T)
  
  r_vents <- raster(lyrs, layer = "phys_vents")
  r_scapes <- raster(lyrs, layer = "scapes_hetero")
  
  r_vgpm <- raster(lyrs, layer = "bio_vgpm")
  r_rls  <- raster(lyrs, layer = "rls_all")
  r_fishing <- raster(lyrs, layer = "fishing_KWH")
  
  # TODO: consider log/log10/normalize transforms of nspp, fish effort 
  #plot(r_vgpm)
  s_lyrs <- stack(
    r_fishing,
    r_vgpm,
    r_nspp,
    r_rls,
    r_vents,
    r_mounts,
    r_scapes)
  names(s_lyrs) <- c(
    "fishing",
    "vgpm",
    "nspp",
    "rls",
    "vents",
    "mounts",
    "scapes")
  terra::writeRaster(s_lyrs, lyrs7_grd)
}
s_lyrs7 <- terra::rast(lyrs7_grd)
  
# plot(s_lyrs7)
```

## Extract layers to planning units

```{r extract & threshold}
# extract feature values
f_0 <- exact_extract(
  s_lyrs7, pu, fun = "mean", append_cols = "hexid", progress = F) %>% 
  tibble() %>% 
  rename_with(~str_replace(., "mean.", ""), everything())

# extra calculations
f_1 <- f_0 %>% 
  mutate(
    fishing = 1/fishing,            # TODO: log(1/fishing)? 
    spp     = rls * nspp,
    benthic = vents + mounts) %>%   # TODO: rescale(vents) + rescale(mounts)? 
  mutate(
    across(where(is.numeric), ~replace_na(., 0)))
summary(f_1)

# rescale
f <- f_1 %>% 
  mutate(
    across(where(is.numeric), rescale))
summary(f)

pu_f <- pu %>%               # 129,906 × 8
  left_join(f, by = "hexid") # 129,906 × 10

get_pu_v_ks <- function(pu_f, v, ks){
  var <- as_label(enquo(v))

  d_v <- pu_f %>% 
    st_drop_geometry() %>% 
    arrange(desc({{v}})) %>% 
    mutate(
      var = var,
      km2 = cumsum(area_km2),
      val = cumsum({{v}})) %>% 
    select(var, km2, val)
  
  val_sum <- d_v %>% pull(val) %>% last()
    
  d_k <- lapply(
    ks,
    function(k){
      i <- max(which(d_v$km2 < d_v$km2[nrow(d_v)]*k))
      tibble(
        var = var, 
        k   = k,
        km2 = d_v$km2[i],
        val = d_v$val[i],
        pct_val = val/val_sum) }) %>% 
    bind_rows()

  p <- d_v %>% 
    ggplot(aes(x = km2, y = val)) + 
    geom_area(fill = "gray", color=NA)
  
  add_k_paths <- function(k, d_k){
    
    # https://colorbrewer2.org/#type=sequential&scheme=Blues&n=3
    col <- c(
      `0.3` = "#9ecae1",
      `0.5` = "#3182bd")[as.character(k)]
    
    x <- d_k %>% filter(k == !!k) %>% pull(km2)
    y <- d_k %>% filter(k == !!k) %>% pull(val)
    y_pct <- d_k %>% filter(k == !!k) %>% pull(pct_val)
    z <- tribble(
      ~x, ~y,
      x,  0,
      x,  y,
      0,  y)
    
    list(
      geom_path(data = z, aes(x,y), color=col),
      annotate(
        "text", x = x, y = y,
        label = glue("{k*100}%: {comma(x, 0.1)} ({percent(y_pct, 0.1)})")))
  }

  p <- p +
    lapply(
      ks,
      add_k_paths,
      d_k) +
    labs(
      x = "area_km2",
      y = var) +
    theme_minimal()
    
  list(
    k=d_k, p=p)
}
# kp1 <- get_pu_v_ks(pu_f, fishing, c(0.3, 0.5))
# names(k_nspp)
# k_nspp$k
# kp1$p

k_p <- sapply(
  c("fishing", "benthic", "scapes", "vgpm", "spp"),
  function(var){
    get_pu_v_ks(pu_f, !!sym(var), c(0.3, 0.5))
  }, 
  simplify = F)

p <- map(k_p, "p")

k <- map(k_p, "k") %>% 
  bind_rows() %>% 
  select(-km2) %>% 
  rename(pct_area = k)

datatable(k) %>% 
  formatPercentage(c("pct_area", "pct_val"), 1)
```

```{r plots, results = 'asis'}
# walk(p, print)
```

## Loop through scenarios

```{r}
wts <- c(0.1, 1, 10)
f_ws <- expand_grid(
  area    = c(0.3, 0.5),
  benthic = wts,
  fishing = wts,
  scapes  = wts,
  spp     = wts,
  vgpm    = wts) %>% 
  mutate(
    scenario = glue(
      "area{area}_benthic{benthic}_fishing{fishing}_scapes{scapes}_spp{spp}_vgpm{vgpm}")) %>% 
  relocate(scenario)
f_ws %>% 
  select(-scenario) %>% 
  datatable()
```

```{r}
get_scenario <- function(area, fishing, benthic, scapes, vgpm, spp, ...){
  
  # ocean area
  a <- area
  
  # feature weights
  f_w <- c(
    benthic = benthic,
    fishing = fishing,
    scapes  = scapes,
    spp     = spp,
    vgpm    = vgpm)
  f_w <- f_w[sort(names(f_w))]
  
  # feature targets (max proportion given ocean area)
  f_t <- k %>% 
    filter(pct_area == !!a) %>% 
    select(var, pct_val) %>% 
    arrange(var) %>% 
    deframe()
  
  # problem ----
  p <- pu_f %>% 
    problem(features = names(f_w), cost_column = "area_pct") %>%
    add_min_shortfall_objective(a) %>% 
    add_relative_targets(f_t) %>%
    add_feature_weights(f_w)
    
  # solve ----
  s <- solve(p, force = T)
  
  # mapview(s %>% filter(solution_1==1), layer.name = s_name)
  
  # gmap(s, "solution_1", s_name)
  
  hexids <- s %>% filter(solution_1==1) %>% pull(hexid)
  
  area_pct <- s %>% filter(solution_1==1) %>% pull(area_pct) %>% sum()
  
  # calculate feature representation statistics based on the prioritization
  features <- eval_target_coverage_summary(p, s[, "solution_1"]) %>% 
    select(feature, relative_held)
  
  list(
    area_pct = a,
    weights  = f_w,
    hexids   = hexids,
    features = features)
}

z <- f_ws %>% 
  slice(1,10,100,300,400) %>%  # TODO: run for ALL
  pmap(get_scenario)

d <- tibble(
  s = z) %>% 
  mutate(
    scenario = map(s, function(x){
      tibble(area = x$area_pct) %>% 
        cbind(
          enframe(x$weights) %>% pivot_wider())
    }),
    hexres   = hex_res,
    hexpct   = 1,
    hexid    = map(s, "hexids"),
    features = map(s, "features"))

d %>% 
  select(scenario, hexres, hexid, hexpct) %>% 
  unnest(c(scenario, hexid)) %>% 
  write_csv("data/solution_hexids.csv")

d %>% 
  select(scenario, features) %>% 
  unnest(c(scenario, features)) %>% 
  write_csv("data/solution_features.csv")

h4 <- readRDS(glue("data/abnj_hex_res4_area.rds")) # 129,906 × 8
h2 <- readRDS(glue("data/abnj_hex_res2_area.rds")) #   3,120 × 8

hexids <- read_csv("data/solution_hexids.csv") %>% 
  filter(
    area == 0.3, 
    benthic == 0.1, fishing == 0.1, scapes == 0.1, spp == 0.1, vgpm == 0.1,
    hexres == 4) %>% 
  pull(hexid)

rda <- "data/scenario_5layers.RData"
# save.image(file = rda)
load(rda)

y <- h4 %>%
  filter(hexid %in% hexids) # 42,675 × 8
#   st_union()

hexids

tibble(
  hexid = hexids) %>% 
  mutate(
    hexid2 = map_chr(hexid, h3_to_parent, 2))

z <- h2 %>% 
  select(hexid) %>% 
  st_join(
    y %>% select(hexid4=hexid), left=F) %>% # 59,842 × 4
  mutate(
    area_km2 = st_area(geometry) %>% 
      set_units(km^2) %>% 
      drop_units()) %>%
  group_by(hexid) %>% 
  summarize(
    area_km2 = sum(area_km2),
    .groups = "drop") %>% 
  left_join(
    h2 %>% 
      mutate(
        area_km2 = st_area(geometry) %>% 
          set_units(km^2) %>% 
          drop_units()) %>% 
      st_drop_geometry() %>% 
      select(hexid, area_km2_whole = area_km2),
    by = "hexid") %>% 
  mutate(
    hexpct = area_km2 / area_km2_whole) # 2,801 × 5


# 1	hexid 	820037fffffffff 
# 2	area_km2 	156658.94 
# 3	geometry 	sfc_POLYGON 
# 4	area_km2_whole 	26109.82 
# 5	hexpct 	6 

b2 <- z %>% 
  filter(hexid == "820037fffffffff")
mapview(b2)

b4ids <- z %>% 
  filter(hexid == "820037fffffffff") %>% 
  st_drop_geometry() %>% 
  pull(hexid4)

b4 <- h4 %>% 
  filter(hexid %in% b4ids) 


mapview(b2) +
  mapview(b4)

h2 %>% 
  select(hexid) %>% 
  st_join(
    y %>% select(hexid4=hexid), left=F) %>% # 59,842 × 4
  filter(hexid == "820037fffffffff")

h2 %>% 
  mutate(
    area_km2 = st_area(geometry) %>% 
      set_units(km^2) %>% 
      drop_units()) %>% 
  st_drop_geometry() %>% 
  select(hexid, area_km2_whole = area_km2) %>% 
  filter(hexid == "820037fffffffff")

26110

mapview(z[1:3,])
summary(h2$area_km2)
summary(h4$area_km2)
hist(z$hexpct)

    # 59,842 × 15


x <- st_intersects(h2, y)
x %>% lengths > 0
class(x)
tibble(x) %>% 
  mutate()

h2 %>% 
  cbind()
  

# Calculate area and tidy up
x_f <- st_intersects(h2, y, sparse=F)

x[[2]]

intersect_pct <- 
   mutate(intersect_area = st_area(.)) %>%   # create new column with shape area
   dplyr::select(NAME, intersect_area) %>%   # only select columns needed to merge
   st_drop_geometry()  # drop geometry as we don't need it



```

```{r}
# install.packages("remotes")
remotes::install_github("crazycapivara/h3-r")
library(h3)

hexid4 <- "8400369ffffffff"
hexid2 <- "820037fffffffff"

tibble(
  hexid = hexids) %>% 
  mutate(
    hexid2 = map_chr(hexid, h3_to_parent, 2))

```



