---
title: "Solution 2: 5 layers"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: hide
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```



## Get planning units as hexagons

```{r}
librarian::shelf(
  BenioffOceanInitiative/bbnj, dplyr, DT,
  exactextractr, fs, ggplot2, glue, here, mapview, 
  prioritizr,
  purrr, raster, scales, sf, stringr, tidyr, units)
source(here("libs/plots.R"))
select <- dplyr::select
mapviewOptions(fgb = FALSE)
mapviewOptions(
  vector.palette = mapviewPalette("mapviewSpectralColors"))
# devtools::load_all(here("~/Github/bbest/prioritizr"))
# devtools::install_local(here("~/Github/bbest/prioritizr"))

hex_geo <- "data/abnj_hex_res2.geojson"

pu_rds  <- glue("{path_ext_remove(hex_geo)}_area.rds")
if (!file.exists(pu_rds)){
  
  pu <- read_sf(hex_geo)
  
  # calculate area
  pu <- pu %>%
    # st_make_valid() %>%      # dateline issues
    filter(st_is_valid(.)) %>% # 8 hexagons dropped 
    mutate(
      area_km2 = st_area(geometry) %>% 
        set_units(km^2) %>% 
        drop_units(),
      area_pct = area_km2 / sum(area_km2))
  # sum(pu$area_pct) # check adds to 12

  saveRDS(pu, file = pu_rds)
} else {
  pu <- readRDS(pu_rds)
  # paste(names(pu), collapse = ", ")
  # hexid, on_dtln, lon, lat, FID, geometry, area_km2, area_pct
}

mapview(pu, zcol="area_pct")
```

## Get layers

```{r}
tifs1 <- list.files(here("../bbnj-scripts/map_layers"), "tif$", full.names = T)
tifs2 <- list.files(here("../bbnj-scripts/presentation_maps"), "tif$", full.names = T)[-1] # drop redundant bio_vgpm.tif
lyrs <- stack(c(tifs1, tifs2))
sort(names(lyrs))

s_nspp <- subset(lyrs, sort(names(lyrs))[26:48])
r_nspp <- calc(s_nspp, sum, na.rm = T)

s_mounts <- subset(lyrs, sort(names(lyrs))[49:51])
r_mounts <- calc(s_mounts, sum, na.rm = T)

r_vents <- raster(lyrs, layer = "phys_vents")
r_scapes <- raster(lyrs, layer = "scapes_hetero")

r_vgpm <- raster(lyrs, layer = "bio_vgpm")
r_rls  <- raster(lyrs, layer = "rls_all")
r_fishing <- raster(lyrs, layer = "fishing_KWH")

# TODO: consider log/log10/normalize transforms of nspp, fish effort 
#plot(r_vgpm)
s_lyrs <- stack(
  r_fishing,
  r_vgpm,
  r_nspp,
  r_rls,
  r_vents,
  r_mounts,
  r_scapes)
names(s_lyrs) <- c(
  "fishing",
  "vgpm",
  "nspp",
  "rls",
  "vents",
  "mounts",
  "scapes")
plot(s_lyrs)
```

## Extract layers to planning units

```{r}
# extract feature values
f <- exact_extract(
  s_lyrs, pu, fun = "mean", append_cols = "hexid", progress = F) %>% 
  tibble() %>% 
  rename_with(~str_replace(., "mean.", ""), everything())

# extra calculations
f <- f %>% 
  mutate(
    spp_1m     = rls * nspp,
    spp_2r     = rescale(rls, to=c(0,1)) * rescale(nspp, to=c(0,1)),
    benthic_1s = vents + mounts,
    benthic_2r = rescale(vents, to=c(0,1)) + rescale(mounts, to=c(0,1)))

# density histograms
f %>% 
  ggplot(aes(x = spp_1m)) + 
  geom_density(lwd = 1, colour = 2, fill = 2, alpha = 0.25)
f %>% 
  ggplot(aes(x = spp_2r)) + 
  geom_density(lwd = 1, colour = 3, fill = 3, alpha = 0.25)
f %>% 
  ggplot(aes(x = benthic_1s)) + 
  geom_density(lwd = 1, colour = 4, fill = 4, alpha = 0.25)
f %>% 
  ggplot(aes(x = benthic_2r)) + 
  geom_density(lwd = 1, colour = 5, fill = 5, alpha = 0.25)

pu <- pu %>% 
  select(hexid, on_dtln, lon, lat, area_km2, area_pct) %>% 
  left_join(
    f, by = "hexid")

mapview(
  pu, zcol = "spp_2r")
```

## Solution: equal weights, 30% area

```{r}
# paste(setdiff(names(f), "hexid"), collapse = ", ")
# fishing, vgpm, nspp, rls, vents, mounts, scapes, spp_1m, spp_2r, benthic_1s, benthic_2r

# ocean area
a <- 0.3
# feature weights
f_w <- c(
  fishing    = 1,
  vgpm       = 1,
  spp_2r     = 1,
  benthic_2r = 1,
  scapes     = 1)

# problem ----
p <- pu %>% 
  problem(features = names(f_w), cost_column = "area_pct") %>%
  add_min_shortfall_objective(a) %>% 
  add_relative_targets(1) %>%
  add_feature_weights(f_w)
  
# solve ----
s <- solve(p, force = T)

mapview(s %>% filter(solution_1==1), layer.name = "solution")

gmap(s, "solution_1", "equal weights")

s %>% filter(solution_1==1) %>% pull(area_pct) %>% sum()

# calculate  feature representation statistics based on the prioritization
s_cov <- eval_target_coverage_summary(p, s[, "solution_1"])
datatable(s_cov)
```

## Solution: weight species, 30% area

```{r}
# paste(setdiff(names(f), "hexid"), collapse = ", ")
# fishing, vgpm, nspp, rls, vents, mounts, scapes, spp_1m, spp_2r, benthic_1s, benthic_2r

# ocean area
a <- 0.3
# feature weights
f_w <- c(
  fishing    = 1,
  vgpm       = 1,
  spp_2r     = 5,
  benthic_2r = 1,
  scapes     = 1)

# problem ----
p <- pu %>% 
  problem(features = names(f_w), cost_column = "area_pct") %>%
  add_min_shortfall_objective(a) %>% 
  add_relative_targets(1) %>%
  add_feature_weights(f_w)
  
# solve ----
s <- solve(p, force = T)

#mapview(s %>% filter(solution_1==1), layer.name = "solution")

gmap(s, "solution_1", "spp = 5 vs rest = 1")

s %>% filter(solution_1==1) %>% pull(area_pct) %>% sum()

# calculate  feature representation statistics based on the prioritization
s_cov <- eval_target_coverage_summary(p, s[, "solution_1"])
datatable(s_cov)
```

## Solution: equal weights, 50% area

```{r}
# paste(setdiff(names(f), "hexid"), collapse = ", ")
# fishing, vgpm, nspp, rls, vents, mounts, scapes, spp_1m, spp_2r, benthic_1s, benthic_2r

# ocean area
a <- 0.3
# feature weights
f_w <- c(
  fishing    = 1,
  vgpm       = 1,
  spp_2r     = 5,
  benthic_2r = 1,
  scapes     = 1)

# problem ----
p <- pu %>% 
  problem(features = names(f_w), cost_column = "area_pct") %>%
  add_min_shortfall_objective(a) %>% 
  add_relative_targets(1) %>%
  add_feature_weights(f_w)
  
# solve ----
s <- solve(p, force = T)

#mapview(s %>% filter(solution_1==1), layer.name = "solution")

gmap(s, "solution_1", "spp = 5 vs rest = 1")

s %>% filter(solution_1==1) %>% pull(area_pct) %>% sum()

# calculate  feature representation statistics based on the prioritization
s_cov <- eval_target_coverage_summary(p, s[, "solution_1"])
datatable(s_cov)
```


