---
title: "Solution 1: initial test with vgpm only"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: hide
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```



## Get planning units as hexagons

```{r}
librarian::shelf(
  BenioffOceanInitiative/bbnj, dplyr, DT,
  exactextractr, fs, glue, here, mapview, 
  prioritizr,
  purrr, raster, sf, stringr, units)
select <- dplyr::select
mapviewOptions(fgb = FALSE)
mapviewOptions(
  vector.palette = mapviewPalette("mapviewSpectralColors"))
# devtools::load_all(here("~/Github/bbest/prioritizr"))
# devtools::install_local(here("~/Github/bbest/prioritizr"))

hex_geo <- "data/abnj_hex_res2.geojson"

pu_rds  <- glue("{path_ext_remove(hex_geo)}_area.rds")
if (!file.exists(pu_rds)){
  
  pu <- read_sf(hex_geo)
  
  # calculate area
  pu <- pu %>%
    # st_make_valid() %>%      # dateline issues
    filter(st_is_valid(.)) %>% # 8 hexagons dropped 
    mutate(
      area_km2 = st_area(geometry) %>% 
        set_units(km^2) %>% 
        drop_units(),
      area_pct = area_km2 / sum(area_km2))
  # sum(pu$area_pct) # check adds to 12

  saveRDS(pu, file = pu_rds)
} else {
  pu <- readRDS(pu_rds)
}

mapview(pu, zcol="area_pct")
```

## Get layers

```{r}
tifs1 <- list.files(here("../bbnj-scripts/map_layers"), "tif$", full.names = T)
tifs2 <- list.files(here("../bbnj-scripts/presentation_maps"), "tif$", full.names = T)[-1] # drop redundant bio_vgpm.tif
lyrs <- stack(c(tifs1, tifs2))
names(lyrs)

r_vgpm <- raster(lyrs, layer = "bio_vgpm")

plot(r_vgpm)
```

## Extract layers to planning units

```{r}
# features with species richness * extinction risk
# f <- exact_extract(
#   subset(s_bio_gmbi, c("nspp_all","rls_all")), pu, fun = "mean", append_cols = "hexid") %>% 
#   tibble() %>% 
#   mutate(
#     bio = mean.nspp_all * mean.rls_all)

# features
f <- exact_extract(
  r_vgpm, pu, fun = "mean", append_cols = "hexid", progress = F) %>% 
  rename(vgpm = mean) %>% 
  tibble() %>% 
  filter(!is.nan(vgpm))

pu <- pu %>% 
  left_join(
    f, by = "hexid")

mapview(
  pu, zcol = "vgpm")

range(pu$vgpm, na.rm = T)
```

## Run prioritizr

```{r}
# problem ----
p <- pu %>% 
  # select(area_pct, vgpm) %>% 
  # filter(!is.na(vgpm)) %>% 
  # filter(area_pct > 1e-6) %>% 
  problem(features = c("vgpm"), cost_column = "area_pct") %>%
  add_min_shortfall_objective(0.3) %>% 
  #add_max_features_objective(0.3) %>% 
  add_relative_targets(1) %>% 
  add_feature_weights(c(1))
  
# solve ----
s <- solve(p, force = T)

mapview(s %>% filter(solution_1==1), layer.name = "solution")

s %>% filter(solution_1==1) %>% pull(area_pct) %>% sum()

# calculate  feature representation statistics based on the prioritization
s_cov <- eval_target_coverage_summary(p, s[, "solution_1"])
datatable(s_cov)
```



